name: firebase_app_check_example
description: Firebase App Check example application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  cupertino_icons: ^0.1.2
  firebase_app_check: ^0.1.2
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
