name: firebase_app_check_example
description: Firebase App Check example application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: any
  cupertino_icons: ^0.1.2
  firebase_app_check: any
  firebase_core: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
