name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  # TODO(jackson): Point this at pub once a stable version is published
  google_sign_in:
    git: git://github.com/flutter/google_sign_in

flutter:
  uses-material-design: true
