name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2"

dependencies:
  firebase_core: ^2.6.0
  firebase_database: ^10.0.12
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
