name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.9.1+hotfix.2'

dependencies:
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
