name: firebase_database_platform_interface
description: A common platform interface for the firebase_database plugin.
version: 0.2.3
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database_platform_interface

dependencies:
  _flutterfire_internals: ^1.1.0
  collection: ^1.14.3
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.6.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'
