name: firebase_analytics_example
description: Demonstrates how to use the firebase_analytics plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_analytics: any
  firebase_core: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
