name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  firebase_core: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
