name: firebase_performance_platform_interface
description: A common platform interface for the firebase_performance plugin.
version: 0.1.1+35
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  _flutterfire_internals: ^1.0.18
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
