name: firebase_performance_platform_interface
description:  A common platform interface for the firebase_performance plugin.
version: 0.1.1+25
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  _flutterfire_internals: ^1.0.8
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  firebase_core_platform_interface: ^4.5.2
  flutter_test:
    sdk: flutter
