# FlutterFire_X naming due to package being take already on Pub.dev.
name: flutterfire_installations
description: A Flutter plugin allowing you to use Firebase Installations.
version: 0.1.0
homepage: https://firebase.flutter.dev/docs/installations/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_installations/firebase_installations

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.1.0
  firebase_installations_platform_interface: ^0.1.0
  firebase_installations_web: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.installations.firebase_installations
        pluginClass: FirebaseInstallationsPlugin
      ios:
        pluginClass: FirebaseInstallationsPlugin
      macos:
        pluginClass: FirebaseInstallationsPlugin
