name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 2.0.0-1.0.nullsafety.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core: ">=0.8.0-1.0.nullsafety.0 <0.8.0-2.0.nullsafety.0"
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  plugin_platform_interface: ^1.1.0-nullsafety.2

dev_dependencies:
  firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.0 <4.0.0-2.0.nullsafety.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
