name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core
version: 0.4.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.core
    iosPrefix: FLT
    pluginClass: FirebaseCorePlugin

dependencies:
  firebase_core_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  meta: "^1.0.5"

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5 <2.0.0"
