name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core
version: 0.4.2+2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.core
        pluginClass: FirebaseCorePlugin
      ios:
        pluginClass: FLTFirebaseCorePlugin

dependencies:
  firebase_core_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  meta: "^1.0.5"

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
