name: firebase_crashlytics_platform_interface
description: A common platform interface for the firebase_crashlytics plugin.
version: 2.0.0-1.0.nullsafety.2
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics_platform_interface

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  collection: ^1.15.0-nullsafety.5
  firebase_core: ">=0.8.0-1.0.nullsafety.1 <0.8.0-2.0.nullsafety.0"
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  plugin_platform_interface: ^1.1.0-nullsafety.2

dev_dependencies:
  firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.1 <4.0.0-2.0.nullsafety.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
