name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: any
  firebase_core: any
  firebase_in_app_messaging: any
  firebase_in_app_messaging_platform_interface: any
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
