name: firebase_app_check_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_web
version: 0.0.7+11

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  _flutterfire_internals: ^1.0.12
  firebase_app_check_platform_interface: ^0.0.5+11
  firebase_core: ^2.4.1
  firebase_core_web: ^2.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_app_check:
    path: ../firebase_app_check
  firebase_core_platform_interface: ^4.5.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckWeb
        fileName: firebase_app_check_web.dart
