name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  firebase_auth: ^4.2.7
  firebase_core: ^2.6.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2

dev_dependencies:
  http: ^0.13.3

flutter:
  uses-material-design: true
