name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  firebase_core: any
  firebase_dynamic_links: any
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0

flutter:
  uses-material-design: true
