name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.12.0'

dependencies:
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.0.17
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0

flutter:
  uses-material-design: true
