name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 0.15.1+1

flutter:
  plugin:
    android:
      package: io.flutter.plugins.firebaseauth
      pluginClass: FirebaseAuthPlugin
    ios:
      pluginClass: FLTFirebaseAuthPlugin

dependencies:
  meta: ^1.0.4
  firebase_core: ^0.4.0
  firebase_auth_platform_interface: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.3.0
  google_sign_in: ^3.0.4
  firebase_dynamic_links: ^0.3.0
  mockito: ^4.1.1
  uuid: ^2.0.2
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
