name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
