name: firebase_performance
description:
  Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance
version: 0.5.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ">=0.8.0-1.0.nullsafety.0 <0.8.0-2.0.nullsafety.0"
dev_dependencies:
  pedantic: ^1.8.0
  http: ^0.12.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.0-nullsafety.15
  e2e: ^0.6.1

dependency_overrides:
  http_parser: ^4.0.0-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseperformance
        pluginClass: FirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin
