name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web

version: 4.2.14

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  cloud_functions_platform_interface: ^5.1.6
  firebase_core: ^1.10.0
  firebase_core_web: ^1.6.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.4.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWeb
        fileName: cloud_functions_web.dart
