name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web

version: 3.3.5

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  _flutterfire_internals: ^1.0.18
  cloud_firestore_platform_interface: ^5.11.5
  collection: ^1.0.0
  firebase_core: ^2.8.0
  firebase_core_web: ^2.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
