name: firebase_database
description: Firebase Database plugin for Flutter.

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.database
    pluginClass: FirebaseDatabasePlugin

dependencies:
  flutter:
    sdk: flutter
