name: firebase_remote_config_example
description: Demonstrates how to use the firebase_remote_config plugin.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  firebase_core: ^2.9.0
  firebase_remote_config: ^4.0.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
