name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  cloud_firestore: any
  firebase_core: any
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
