name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.4.3+1

flutter:
  uses-material-design: true
