name: firebase_firestore_odm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/cloud_firestore/**"
      - "packages/cloud_firestore_odm/**"
      - ".github/workflows/firebase_firestore_odm.yaml"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*cloud_firestore*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*cloud_firestore_odm_example*"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
        with:
          run-bootstrap: false
      - name: "Bootstrap Workspace"
        run: |
          melos bootstrap --scope="*firebase_core*" --scope="$FLUTTERFIRE_PLUGIN_SCOPE"
          melos run odm:example_build_runner:build
          melos run odm:generator_test_build_runner:build
          # Needed because generating breaks the local linking of melos
          melos bootstrap --scope="*firebase_core*" --scope="$FLUTTERFIRE_PLUGIN_SCOPE"
      - name: "Flutter Test"
        run: melos run odm:test:flutter --no-select
      - name: "Dart Test"
        run: melos run odm:test:dart --no-select

  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
        with:
          run-bootstrap: false
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "Bootstrap Workspace"
        run: |
          melos bootstrap --scope="*firebase_core*" --scope="$FLUTTERFIRE_PLUGIN_SCOPE"
          melos run odm:example_build_runner:build
          melos run odm:generator_test_build_runner:build
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-example.sh web
