name: firebase_firestore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - "packages/cloud_firestore/**"
      - ".github/workflows/firebase_firestore.yaml"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*cloud_firestore*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*cloud_firestore_example*"

jobs:
  android:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
        with:
          run-bootstrap: false
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          # Firebase Firestore works without Google Play Services, so we don't use the `googleapis`
          # emulator target as it's considerably slower on CI.
          target: default
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-example.sh android

  apple:
    runs-on: macos-12
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
        with:
          run-bootstrap: false
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive iOS Example"
        run: ./.github/workflows/scripts/drive-example.sh ios
      - name: "Build MacOS Example"
        run: ./.github/workflows/scripts/build-example.sh macos
      - name: "Reset Firestore Emulator"
        run: cd ./.github/workflows/scripts && ./reset-firestore-emulator.sh
      - name: "Drive MacOS Example"
        run: ./.github/workflows/scripts/drive-example.sh macos

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@v1
        with:
          run-bootstrap: false
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-example.sh web
