name: firebase_in_app_messaging

on:
  pull_request:
    paths:
      - "packages/firebase_in_app_messaging/**"
      - ".github/workflows/firebase_in_app_messaging.yaml"
      # Ensure this workflow runs if the Firebase Android SDK version gets bumped.
      - "packages/firebase_core/firebase_core/android/gradle.properties"
      # Ensure this workflow runs if the Firebase iOS SDK version gets bumped.
      - "packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_in_app_messaging*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*firebase_in_app_messaging_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          # Firebase Dynamic Links requires Google Play Services, so we use the `google_apis`
          target: google_apis
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-example.sh android

  ios:
    runs-on: macos-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --enable-macos-desktop
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios
      - name: "Drive iOS Example"
        run: ./.github/workflows/scripts/drive-example.sh ios
